%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(ack_pb).
-define(ack_pb, true).

-define(ack_pb_gpb_version, "4.21.5").


-ifndef('EXECASSIGNMENTACK_PB_H').
-define('EXECASSIGNMENTACK_PB_H', true).
-record('ExecAssignmentAck',
        {assignment_id = <<>>   :: unicode:chardata() | undefined, % = 1, optional
         status = <<>>          :: unicode:chardata() | undefined, % = 2, optional
         message = <<>>         :: unicode:chardata() | undefined, % = 3, optional
         request_id = <<>>      :: unicode:chardata() | undefined, % = 4, optional
         trace_id = <<>>        :: unicode:chardata() | undefined, % = 5, optional
         tenant_id = <<>>       :: unicode:chardata() | undefined, % = 6, optional
         acknowledged_at = 0    :: integer() | undefined % = 7, optional, 64 bits
        }).
-endif.

-endif.
