#!/bin/bash
# @file setup_test_environment.sh
# @brief Setup test environment for router tests
# @description Configures test environment, checks dependencies, and prepares test infrastructure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROUTER_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_ROOT="$(cd "$ROUTER_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
NATS_MOCK_MODE=${NATS_MOCK_MODE:-true}
TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
GRPC_ENABLED=${GRPC_ENABLED:-false}
GRPC_PORT=${GRPC_PORT:-0}
METRICS_PORT=${METRICS_PORT:-9091}

echo "=========================================="
echo "Router Test Environment Setup"
echo "=========================================="
echo ""

# Check Erlang/OTP installation
echo -n "Checking Erlang/OTP installation... "
if command -v erl >/dev/null 2>&1; then
    ERL_VERSION=$(erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell 2>&1 | tr -d '\n')
    echo -e "${GREEN}✓${NC} Found: OTP $ERL_VERSION"
else
    echo -e "${RED}✗${NC} Erlang/OTP not found"
    echo "  Please install Erlang/OTP (version 25+ recommended)"
    exit 1
fi

# Check rebar3 installation
echo -n "Checking rebar3 installation... "
if command -v rebar3 >/dev/null 2>&1; then
    REBAR3_VERSION=$(rebar3 --version 2>&1 | head -1)
    echo -e "${GREEN}✓${NC} Found: $REBAR3_VERSION"
else
    echo -e "${RED}✗${NC} rebar3 not found"
    echo "  Please install rebar3: https://www.rebar3.org/docs/getting-started"
    exit 1
fi

# Check PropEr installation (for property-based tests)
echo -n "Checking PropEr installation... "
cd "$ROUTER_DIR"
if rebar3 as test tree 2>&1 | grep -q "proper"; then
    echo -e "${GREEN}✓${NC} PropEr found in dependencies"
else
    echo -e "${YELLOW}⚠${NC} PropEr not found (property tests will be skipped)"
fi

# Check meck installation (for mocking)
echo -n "Checking meck installation... "
if rebar3 as test tree 2>&1 | grep -q "meck"; then
    echo -e "${GREEN}✓${NC} meck found in dependencies"
else
    echo -e "${YELLOW}⚠${NC} meck not found (mocking tests will fail)"
fi

# Compile test dependencies
echo ""
echo "Compiling test dependencies..."
cd "$ROUTER_DIR"
if rebar3 as test get-deps >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Test dependencies fetched"
else
    echo -e "${YELLOW}⚠${NC} Some dependencies may be missing"
fi

# Compile test build
echo ""
echo "Compiling test build..."
if rebar3 as test compile >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Test build compiled successfully"
else
    echo -e "${RED}✗${NC} Test build compilation failed"
    echo "  Run 'rebar3 as test compile' for details"
    exit 1
fi

# Check NATS (optional, for integration tests)
echo ""
echo -n "Checking NATS availability... "
if [ "$NATS_MOCK_MODE" = "false" ]; then
    if command -v nats-server >/dev/null 2>&1; then
        echo -e "${GREEN}✓${NC} NATS server found"
        echo "  Starting NATS server for tests..."
        # NATS will be started by test suites if needed
    else
        echo -e "${YELLOW}⚠${NC} NATS server not found (using mock mode)"
        echo "  Install NATS: https://docs.nats.io/running-a-nats-service/introduction/installation"
        NATS_MOCK_MODE=true
    fi
else
    echo -e "${GREEN}✓${NC} Using NATS mock mode (no external NATS required)"
fi

# Create test directories
echo ""
echo "Creating test directories..."
mkdir -p "$ROUTER_DIR/test_results"
mkdir -p "$ROUTER_DIR/test_logs"
mkdir -p "$ROUTER_DIR/coverage"
echo -e "${GREEN}✓${NC} Test directories created"

# Export environment variables
echo ""
echo "Setting test environment variables..."
export NATS_MOCK_MODE=$NATS_MOCK_MODE
export TELEMETRY_ENABLED=$TELEMETRY_ENABLED
export GRPC_ENABLED=$GRPC_ENABLED
export GRPC_PORT=$GRPC_PORT
export METRICS_PORT=$METRICS_PORT
export ERL_FLAGS="+K true +A 4"

echo "  NATS_MOCK_MODE=$NATS_MOCK_MODE"
echo "  TELEMETRY_ENABLED=$TELEMETRY_ENABLED"
echo "  GRPC_ENABLED=$GRPC_ENABLED"
echo "  GRPC_PORT=$GRPC_PORT"
echo "  METRICS_PORT=$METRICS_PORT"

# Create test environment file
cat > "$ROUTER_DIR/.test_env" <<EOF
# Router Test Environment Configuration
# Generated by setup_test_environment.sh

NATS_MOCK_MODE=$NATS_MOCK_MODE
TELEMETRY_ENABLED=$TELEMETRY_ENABLED
GRPC_ENABLED=$GRPC_ENABLED
GRPC_PORT=$GRPC_PORT
METRICS_PORT=$METRICS_PORT
ERL_FLAGS="+K true +A 4"
EOF

echo ""
echo "=========================================="
echo -e "${GREEN}Test environment setup complete!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Run fast tests:     ./scripts/test_fast.sh"
echo "  2. Run slow tests:      ./scripts/test_slow.sh"
echo "  3. Run CP1 smoke tests: ./scripts/test_cp1_smoke.sh"
echo "  4. Run specific suite:  rebar3 ct --suite test/<suite_name>_SUITE"
echo ""
echo "Test environment configuration saved to: .test_env"
echo ""

