%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(flow_pb).
-define(flow_pb, true).

-define(flow_pb_gpb_version, "4.21.5").


-ifndef('MESSAGE_PB_H').
-define('MESSAGE_PB_H', true).
-record('Message',
        {message_id = <<>>      :: unicode:chardata() | undefined, % = 1, optional
         tenant_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         trace_id = <<>>        :: unicode:chardata() | undefined, % = 3, optional
         message_type = <<>>    :: unicode:chardata() | undefined, % = 4, optional
         payload = <<>>         :: iodata() | undefined, % = 5, optional
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined, % = 6
         timestamp_ms = 0       :: integer() | undefined % = 7, optional, 64 bits
        }).
-endif.

-ifndef('ROUTEREQUEST_PB_H').
-define('ROUTEREQUEST_PB_H', true).
-record('RouteRequest',
        {message = undefined    :: flow_pb:'Message'() | undefined, % = 1, optional
         policy_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         context = []           :: [{unicode:chardata(), unicode:chardata()}] | undefined % = 3
        }).
-endif.

-ifndef('ROUTEDECISION_PB_H').
-define('ROUTEDECISION_PB_H', true).
-record('RouteDecision',
        {provider_id = <<>>     :: unicode:chardata() | undefined, % = 1, optional
         reason = <<>>          :: unicode:chardata() | undefined, % = 2, optional
         priority = 0           :: integer() | undefined, % = 3, optional, 32 bits
         expected_latency_ms = 0 :: integer() | undefined, % = 4, optional, 64 bits
         expected_cost = 0.0    :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 5, optional
         metadata = []          :: [{unicode:chardata(), unicode:chardata()}] | undefined % = 6
        }).
-endif.

-ifndef('UPSERTPOLICYREQUEST_PB_H').
-define('UPSERTPOLICYREQUEST_PB_H', true).
-record('UpsertPolicyRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         policy = undefined     :: flow_pb:'AdminPolicy'() | undefined % = 2, optional
        }).
-endif.

-ifndef('UPSERTPOLICYRESPONSE_PB_H').
-define('UPSERTPOLICYRESPONSE_PB_H', true).
-record('UpsertPolicyResponse',
        {ok = false             :: boolean() | 0 | 1 | undefined % = 1, optional
        }).
-endif.

-ifndef('DELETEPOLICYREQUEST_PB_H').
-define('DELETEPOLICYREQUEST_PB_H', true).
-record('DeletePolicyRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         policy_id = <<>>       :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('DELETEPOLICYRESPONSE_PB_H').
-define('DELETEPOLICYRESPONSE_PB_H', true).
-record('DeletePolicyResponse',
        {ok = false             :: boolean() | 0 | 1 | undefined % = 1, optional
        }).
-endif.

-ifndef('GETPOLICYREQUEST_PB_H').
-define('GETPOLICYREQUEST_PB_H', true).
-record('GetPolicyRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         policy_id = <<>>       :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('GETPOLICYRESPONSE_PB_H').
-define('GETPOLICYRESPONSE_PB_H', true).
-record('GetPolicyResponse',
        {policy = undefined     :: flow_pb:'AdminPolicy'() | undefined % = 1, optional
        }).
-endif.

-ifndef('LISTPOLICIESREQUEST_PB_H').
-define('LISTPOLICIESREQUEST_PB_H', true).
-record('ListPoliciesRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('LISTPOLICIESRESPONSE_PB_H').
-define('LISTPOLICIESRESPONSE_PB_H', true).
-record('ListPoliciesResponse',
        {policies = []          :: [flow_pb:'AdminPolicy'()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('ADMINPOLICY_PB_H').
-define('ADMINPOLICY_PB_H', true).
-record('AdminPolicy',
        {policy_id = <<>>       :: unicode:chardata() | undefined, % = 1, optional
         providers = []         :: [flow_pb:'AdminProvider'()] | undefined, % = 2, repeated
         sticky = false         :: boolean() | 0 | 1 | undefined, % = 3, optional
         rules = []             :: [flow_pb:'AdminRule'()] | undefined % = 4, repeated
        }).
-endif.

-ifndef('ADMINPROVIDER_PB_H').
-define('ADMINPROVIDER_PB_H', true).
-record('AdminProvider',
        {id = <<>>              :: unicode:chardata() | undefined, % = 1, optional
         weight = 0.0           :: float() | integer() | infinity | '-infinity' | nan | undefined % = 2, optional
        }).
-endif.

-ifndef('ADMINRULE_PB_H').
-define('ADMINRULE_PB_H', true).
-record('AdminRule',
        {match = <<>>           :: unicode:chardata() | undefined, % = 1, optional
         prefer = []            :: [unicode:chardata()] | undefined, % = 2, repeated
         fallback = <<>>        :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-endif.
%% Admin: CP/Validators messages (added without regenerating gpb)
-ifndef('GETCHECKPOINTSTATUSREQUEST_PB_H').
-define('GETCHECKPOINTSTATUSREQUEST_PB_H', true).
-record('GetCheckpointStatusRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('CHECKPOINTSTATUS_PB_H').
-define('CHECKPOINTSTATUS_PB_H', true).
-record('CheckpointStatus',
        {current_cp = <<>>      :: unicode:chardata() | undefined, % = 1, optional
         cp2_plus_allowed = false :: boolean() | 0 | 1 | undefined, % = 2, optional
         updated_at_ms = 0      :: integer() | undefined % = 3, optional, 64 bits
        }).
-endif.

-ifndef('GETCHECKPOINTSTATUSRESPONSE_PB_H').
-define('GETCHECKPOINTSTATUSRESPONSE_PB_H', true).
-record('GetCheckpointStatusResponse',
        {status = undefined     :: flow_pb:'CheckpointStatus'() | undefined % = 1, optional
        }).
-endif.

-ifndef('GETVALIDATORSHEALTHREQUEST_PB_H').
-define('GETVALIDATORSHEALTHREQUEST_PB_H', true).
-record('GetValidatorsHealthRequest',
        {tenant_id = <<>>       :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('VALIDATORSTATUS_PB_H').
-define('VALIDATORSTATUS_PB_H', true).
-record('ValidatorStatus',
        {name = <<>>            :: unicode:chardata() | undefined, % = 1, optional
         status = <<>>          :: unicode:chardata() | undefined, % = 2, optional
         timestamp_ms = 0       :: integer() | undefined, % = 3, optional, 64 bits
         details = <<>>         :: unicode:chardata() | undefined % = 4, optional
        }).
-endif.

-ifndef('GETVALIDATORSHEALTHRESPONSE_PB_H').
-define('GETVALIDATORSHEALTHRESPONSE_PB_H', true).
-record('GetValidatorsHealthResponse',
        {validators = []        :: [flow_pb:'ValidatorStatus'()] | undefined % = 1, repeated
        }).
-endif.
